OrdererOrgs:
  - Name: Orderer
    Domain: university.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Block33
    Domain: block33.university.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Block34
    Domain: block34.university.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Block35
    Domain: block35.university.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

